# Generated by Django 4.2.30 on 2026-05-21 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tramites', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('anio', models.IntegerField(choices=[(1, '1er año'), (2, '2do año'), (3, '3er año')])),
                ('ciclo', models.IntegerField(choices=[(1, 'Ciclo I'), (2, 'Ciclo II'), (3, 'Ciclo III'), (4, 'Ciclo IV'), (5, 'Ciclo V'), (6, 'Ciclo VI')])),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('duracion', models.IntegerField(choices=[(2, '2 años'), (3, '3 años')])),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('certificado_notas', 'Certificado de Notas'), ('certificado_estudios', 'Certificado de Estudios'), ('constancia', 'Constancia de Estudios'), ('titulo', 'Título Profesional')], max_length=40)),
                ('estado', models.CharField(choices=[('solicitado', 'Solicitado'), ('en_proceso', 'En Proceso'), ('listo', 'Listo para recoger'), ('entregado', 'Entregado')], default='solicitado', max_length=20)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_tramites.alumno')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='Beca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('excelencia', 'Beca Excelencia'), ('necesidad', 'Beca por Necesidad'), ('deportiva', 'Beca Deportiva'), ('convenio', 'Beca por Convenio')], max_length=30)),
                ('porcentaje', models.IntegerField(help_text='Porcentaje de descuento (ej: 50, 100)')),
                ('estado', models.CharField(choices=[('solicitada', 'Solicitada'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('vigente', 'Vigente'), ('finalizada', 'Finalizada')], default='solicitada', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='becas', to='app_tramites.alumno')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='app_tramites.carrera'),
        ),
        migrations.CreateModel(
            name='Pension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(choices=[(1, 'Enero'), (2, 'Febrero'), (3, 'Marzo'), (4, 'Abril'), (5, 'Mayo'), (6, 'Junio'), (7, 'Julio'), (8, 'Agosto'), (9, 'Septiembre'), (10, 'Octubre'), (11, 'Noviembre'), (12, 'Diciembre')])),
                ('anio', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pensiones', to='app_tramites.alumno')),
            ],
            options={
                'ordering': ['-anio', '-mes'],
                'unique_together': {('alumno', 'mes', 'anio')},
            },
        ),
    ]
