# Generated by Django 4.2.30 on 2026-05-21 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tramites', '0002_alumno_carrera_documento_beca_alumno_carrera_pension'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodotramite',
            name='enlace',
            field=models.CharField(blank=True, help_text='URL opcional a la que redirige este nodo (ej: /alumnos/)', max_length=500),
        ),
    ]
