# Generated by Django 4.2.30 on 2026-05-22 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_tramites', '0003_nodotramite_enlace'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodotramite',
            name='tipo',
            field=models.CharField(choices=[('categoria', 'Categoría'), ('tramite', 'Trámite'), ('documento', 'Documento'), ('accion', 'Acción')], default='categoria', max_length=20),
        ),
        migrations.AlterField(
            model_name='beca',
            name='porcentaje',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nodotramite',
            name='enlace',
            field=models.CharField(blank=True, help_text='URL opcional', max_length=500),
        ),
    ]
