# Generated by Django 4.2.30 on 2026-05-22 06:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_tramites', '0004_nodotramite_tipo_alter_beca_porcentaje_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('creditos', models.IntegerField(default=3)),
                ('horas_teoria', models.IntegerField(default=2)),
                ('horas_practica', models.IntegerField(default=2)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CursoCarrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciclo', models.IntegerField(choices=[(1, 'Ciclo I'), (2, 'Ciclo II'), (3, 'Ciclo III'), (4, 'Ciclo IV'), (5, 'Ciclo V'), (6, 'Ciclo VI')])),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='malla', to='app_tramites.carrera')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='app_tramites.curso')),
            ],
            options={
                'ordering': ['ciclo', 'curso__nombre'],
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('apellido', models.CharField(max_length=200)),
                ('especialidad', models.CharField(choices=[('informatica', 'Informática'), ('administracion', 'Administración'), ('contabilidad', 'Contabilidad'), ('electronica', 'Electrónica'), ('mecanica', 'Mecánica'), ('enfermeria', 'Enfermería'), ('otro', 'Otro')], default='otro', max_length=30)),
                ('correo_institucional', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_ingreso', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='alumno',
            name='correo_institucional',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='direccion',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='alumno',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alumno',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='nodotramite',
            name='enlace',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pension', 'Pensión'), ('matricula', 'Matrícula'), ('derecho', 'Derecho de examen'), ('certificado', 'Certificado'), ('otro', 'Otro')], max_length=20)),
                ('concepto', models.CharField(max_length=300)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=9)),
                ('metodo', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia bancaria'), ('pos', 'POS / Tarjeta'), ('yape', 'Yape / Plin')], default='efectivo', max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('completado', 'Completado'), ('anulado', 'Anulado')], default='pendiente', max_length=20)),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('num_operacion', models.CharField(blank=True, max_length=50, verbose_name='N° operación')),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app_tramites.alumno')),
                ('pension', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pago', to='app_tramites.pension')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pago_vencido', 'Pago Vencido'), ('pago_proximo', 'Pago Próximo'), ('nota_cargada', 'Nota Cargada'), ('comunicado', 'Comunicado'), ('matricula', 'Matrícula'), ('sistema', 'Sistema')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('alumno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app_tramites.alumno')),
                ('docente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='app_tramites.docente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo', models.CharField(choices=[('2024-I', '2024-I'), ('2024-II', '2024-II'), ('2025-I', '2025-I'), ('2025-II', '2025-II'), ('2026-I', '2026-I'), ('2026-II', '2026-II')], max_length=10)),
                ('ciclo', models.IntegerField(choices=[(1, 'Ciclo I'), (2, 'Ciclo II'), (3, 'Ciclo III'), (4, 'Ciclo IV'), (5, 'Ciclo V'), (6, 'Ciclo VI')])),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('retirada', 'Retirada'), ('observada', 'Observada'), ('finalizada', 'Finalizada')], default='activa', max_length=20)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('observacion', models.TextField(blank=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matriculas', to='app_tramites.alumno')),
                ('cursos', models.ManyToManyField(blank=True, related_name='matriculas', to='app_tramites.cursocarrera')),
            ],
            options={
                'ordering': ['-periodo'],
                'unique_together': {('alumno', 'periodo')},
            },
        ),
        migrations.AddField(
            model_name='cursocarrera',
            name='docente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cursos_asignados', to='app_tramites.docente'),
        ),
        migrations.CreateModel(
            name='Comunicado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(choices=[('general', 'General'), ('academico', 'Académico'), ('financiero', 'Financiero'), ('urgente', 'Urgente')], default='general', max_length=20)),
                ('destinatario', models.CharField(choices=[('todos', 'Todos'), ('alumnos', 'Solo Alumnos'), ('docentes', 'Solo Docentes'), ('carrera', 'Por Carrera')], default='todos', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comunicados', to='app_tramites.carrera')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota_p1', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Parcial 1')),
                ('nota_p2', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Parcial 2')),
                ('nota_final', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Final')),
                ('promedio', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('aprobado', models.BooleanField(blank=True, null=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_tramites.cursocarrera')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='app_tramites.matricula')),
            ],
            options={
                'ordering': ['curso__curso__nombre'],
                'unique_together': {('matricula', 'curso')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cursocarrera',
            unique_together={('carrera', 'curso', 'ciclo')},
        ),
    ]
