# Generated by Django 4.2.30 on 2026-05-22 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_tramites', '0005_curso_cursocarrera_docente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beca',
            name='nodo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='becas_asociadas', to='app_tramites.nodotramite'),
        ),
        migrations.AddField(
            model_name='documento',
            name='nodo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_asociados', to='app_tramites.nodotramite'),
        ),
        migrations.AddField(
            model_name='matricula',
            name='nodo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matriculas_asociadas', to='app_tramites.nodotramite'),
        ),
        migrations.AddField(
            model_name='pension',
            name='nodo_tramite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pensiones_asociadas', to='app_tramites.nodotramite'),
        ),
    ]
